# Generated by Django 5.0.2 on 2024-03-26 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.station'),
        ),
    ]
