# Generated by Django 5.0.2 on 2024-03-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_route_station'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
    ]
