# Generated by Django 5.0.2 on 2024-03-26 16:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('arrival_time', models.TimeField()),
                ('distance', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='home.train')),
            ],
        ),
    ]
