# Generated by Django 5.0.2 on 2024-03-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_helper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='charge',
            field=models.IntegerField(null=True),
        ),
    ]
