# Generated by Django 5.0.2 on 2024-04-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_travel_travel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='about',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
